version: "2"
services:
  web:
    build: ./mynewproject
    command: python ./manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: 'postgres://postgres@db/postgres'
    depends_on:
    - db

  db:
    image: postgres:9.4
